#!/bin/sh
# Author: Jonas Schubert <guepardoapps@gmail.com>

. /lib/lsb/init-functions

do_start()
{
	echo "Starting wireless control server: "
	/bin/wirelesscontrol &
  	log_success_msg "done"
	return 0
}

do_stop()
{
	echo  "Stopping wireless control server: "
	pkill wirelesscontrol > /dev/null
	log_success_msg "done"
	return 0
}


### main logic ###
case "$1" in
  start)
        do_start
        ;;
  stop)
        do_stop
        ;;
  status)
        status wirelesscontrol
        ;;
  restart|reload|condrestart)
        do_stop
        do_start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0
